#!/bin/bash

# Run DaCapo benchmarks with ET3+Merlin death tracking

set -e

# Configuration
DACAPO_JAR="/Users/luka/Desktop/Honors_Thesis/dacapo-23.11-MR2-chopin/dacapo-23.11-MR2-chopin.jar"
ET3_AGENT="/Users/luka/Desktop/Honors_Thesis/et2-java/javassist-inst/et2-instrumenter/target/instrumenter-1.0-SNAPSHOT-jar-with-dependencies.jar"
OUTPUT_DIR="/Users/luka/Desktop/Honors_Thesis/et2-java/dacapo_traces"

# Benchmark to run (default: avrora, a small one for testing)
BENCHMARK="${1:-avrora}"
SIZE="${2:-small}"

# Color output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}DaCapo + ET3 + Merlin Death Tracking${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""

# Check if DaCapo jar exists
if [ ! -f "$DACAPO_JAR" ]; then
    echo -e "${RED}ERROR: DaCapo jar not found at $DACAPO_JAR${NC}"
    exit 1
fi

# Check if ET3 agent exists
if [ ! -f "$ET3_AGENT" ]; then
    echo -e "${RED}ERROR: ET3 agent not found. Please build it first:${NC}"
    echo "  cd javassist-inst/et2-instrumenter && mvn clean compile package"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"

echo -e "${YELLOW}Benchmark:${NC} $BENCHMARK"
echo -e "${YELLOW}Size:${NC} $SIZE"
echo -e "${YELLOW}Output:${NC} $OUTPUT_DIR"
echo ""

# List available benchmarks
if [ "$BENCHMARK" = "list" ]; then
    echo "Available DaCapo benchmarks:"
    java -jar "$DACAPO_JAR" -l
    exit 0
fi

echo -e "${GREEN}Running $BENCHMARK benchmark with ET3+Merlin...${NC}"
echo "This may take a few minutes..."
echo ""

# Run the benchmark
START_TIME=$(date +%s)

# Note: --no-validation is required because ET3's bytecode instrumentation
# causes DaCapo to detect modifications and invalidate the run
java -javaagent:"$ET3_AGENT" \
     -Xmx2g \
     -jar "$DACAPO_JAR" \
     --no-validation \
     -s "$SIZE" \
     "$BENCHMARK" 2>&1 | tee "${BENCHMARK}_${SIZE}_output.log"

END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

echo ""
echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}Benchmark Complete!${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo "Time: ${ELAPSED}s"
echo ""

# Analyze the trace
if [ -f "trace" ]; then
    TRACE_SIZE=$(wc -c < trace | awk '{print $1}')
    TRACE_SIZE_MB=$((TRACE_SIZE / 1024 / 1024))
    
    echo "Trace Analysis:"
    echo "==============="
    echo "Trace file: trace"
    echo "Size: ${TRACE_SIZE_MB} MB (${TRACE_SIZE} bytes)"
    echo ""
    
    # Count record types
    ALLOCS=$(grep -c "^[NA]" trace || echo "0")
    METHODS=$(grep -c "^M" trace || echo "0")
    EXITS=$(grep -c "^E" trace || echo "0")
    UPDATES=$(grep -c "^U" trace || echo "0")
    DEATHS=$(grep -c "^D" trace || echo "0")
    
    echo "Record Counts:"
    echo "  Allocations (N/A): $ALLOCS"
    echo "  Method Entries (M): $METHODS"
    echo "  Method Exits (E):  $EXITS"
    echo "  Field Updates (U): $UPDATES"
    echo "  Deaths (D):        $DEATHS"
    echo ""
    
    if [ "$DEATHS" -gt 0 ]; then
        echo -e "${GREEN}✓ Death records generated by Merlin!${NC}"
        echo ""
        echo "Sample death records (first 5):"
        grep "^D" trace | head -5
        echo ""
        
        # Rename trace with benchmark name
        mv trace "${BENCHMARK}_${SIZE}_trace.txt"
        mv methods.list "${BENCHMARK}_${SIZE}_methods.list" 2>/dev/null || true
        mv fields.list "${BENCHMARK}_${SIZE}_fields.list" 2>/dev/null || true
        mv classs.list "${BENCHMARK}_${SIZE}_classs.list" 2>/dev/null || true
        
        echo "Files saved:"
        echo "  ${BENCHMARK}_${SIZE}_trace.txt"
        echo "  ${BENCHMARK}_${SIZE}_methods.list"
        echo "  ${BENCHMARK}_${SIZE}_fields.list"
        echo "  ${BENCHMARK}_${SIZE}_classs.list"
        echo "  ${BENCHMARK}_${SIZE}_output.log"
    else
        echo -e "${YELLOW}⚠ No death records found (unusual - may indicate an issue)${NC}"
    fi
else
    echo -e "${RED}ERROR: Trace file not generated${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}======================================${NC}"
echo "Trace generation complete!"
echo "Location: $OUTPUT_DIR"
echo -e "${GREEN}======================================${NC}"
