#!/bin/bash

# Test script for ET3 with integrated Merlin death tracking

set -e

echo "========================================"
echo "ET3 with Integrated Merlin Algorithm"
echo "========================================"
echo ""

cd /Users/luka/Desktop/Honors_Thesis/et2-java

# Step 1: Rebuild ET3 agent with integrated Merlin
echo "[1/4] Rebuilding ET3 agent with Merlin integration..."
cd javassist-inst/et2-instrumenter
mvn clean compile package > /dev/null 2>&1
cd ../..
echo "  ✓ Build complete"

# Step 2: Prepare test
echo "[2/4] Preparing test..."
rm -rf trace_output_integrated
mkdir -p trace_output_integrated
javac -d trace_output_integrated java/SimpleTrace.java
echo "  ✓ Test compiled"

# Step 3: Run test with integrated ET3+Merlin
echo "[3/4] Running SimpleTrace with integrated ET3+Merlin..."
cd trace_output_integrated
java -javaagent:../javassist-inst/et2-instrumenter/target/instrumenter-1.0-SNAPSHOT-jar-with-dependencies.jar SimpleTrace > program_output.txt 2>&1
cd ..
echo "  ✓ Trace generated"

# Step 4: Analyze trace
echo "[4/4] Analyzing generated trace..."
echo ""
echo "========================================"
echo "Results"
echo "========================================"

if [ -f "trace_output_integrated/trace" ]; then
    ALLOCS=$(grep -c "^[NA]" trace_output_integrated/trace || echo "0")
    UPDATES=$(grep -c "^U" trace_output_integrated/trace || echo "0")
    METHODS=$(grep -c "^M" trace_output_integrated/trace || echo "0")
    EXITS=$(grep -c "^E" trace_output_integrated/trace || echo "0")
    DEATHS=$(grep -c "^D" trace_output_integrated/trace || echo "0")
    
    echo "Trace file: trace_output_integrated/trace"
    echo ""
    echo "Event Counts:"
    echo "  Allocations (N/A): $ALLOCS"
    echo "  Field Updates (U): $UPDATES"
    echo "  Method Entries (M): $METHODS"
    echo "  Method Exits (E):  $EXITS"
    echo "  Deaths (D):        $DEATHS"
    echo ""
    
    if [ "$DEATHS" -gt 0 ]; then
        echo "✓ SUCCESS: Death records generated by ET3!"
        echo ""
        echo "Sample Death Records:"
        grep "^D" trace_output_integrated/trace | head -5
        echo ""
        echo "ET3 now produces complete traces with:"
        echo "  ✓ Object allocations"
        echo "  ✓ Method entry/exit"
        echo "  ✓ Field updates"
        echo "  ✓ Object deaths (Merlin algorithm)"
        echo ""
        echo "Deaths are detected at method boundaries for accuracy"
        echo "to the nearest method call/exit, as specified."
    else
        echo "⚠ WARNING: No death records found"
        echo "This may be normal for very simple programs"
    fi
else
    echo "ERROR: Trace file not generated"
    exit 1
fi

echo ""
echo "========================================"
echo "View the trace:"
echo "  less trace_output_integrated/trace"
echo "========================================"
